# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqAZx3IOHsDn4PbeKjHcDpI3QYrI6Bce
"""

!pip install streamlit
!pip install joblib

import streamlit as st
import pandas as pd
import joblib

st.title("🏦 Indian Bank Loan Prediction System")

uploaded_file = st.file_uploader("Upload Test CSV File", type=["csv"])

model_choice = st.selectbox(
    "Select Model",
    ["Logistic Regression", "Decision Tree", "KNN",
     "Naive Bayes", "Random Forest", "XGBoost"]
)

if uploaded_file:
    data = pd.read_csv(uploaded_file)

    model_dict = {
        "Logistic Regression": "model/lr.pkl",
        "Decision Tree": "model/dt.pkl",
        "KNN": "model/knn.pkl",
        "Naive Bayes": "model/nb.pkl",
        "Random Forest": "model/rf.pkl",
        "XGBoost": "model/xgb.pkl"
    }

    model = joblib.load(model_dict[model_choice])
    prediction = model.predict(data)

    st.write("### Predictions")
    st.write(prediction)